language: java
jdk:
  - oraclejdk7
  - openjdk7

before_install:
  - wget -P $TRAVIS_BUILD_DIR/ https://www.dropbox.com/s/hyuekqd3ev8sqcm/dominio.jar
  - wget -P $TRAVIS_BUILD_DIR/ https://www.dropbox.com/s/rwp77gpptpgpdpr/cliente.jar